model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.DAE
  params:
    monitor: val/mask_loss
    embed_dim: 7
    # ckpt_path: "pretrained_DLDM/DLDM_pretrained/DAE_epoch=000053.ckpt"
    lossconfig:
      target: ldm.modules.losses.LPIPS_DAE_integ_loss
      params:
        kl_weight: 1.0e-06
    enc_config:
      double_z: true
      z_channels: 7
      resolution: 256
      in_channels: 5
      out_ch: 1
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    dec_config:
      double_z: true
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 1
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    mask_dec_config:
      in_channels: 1
      out_channels: 1
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    wrap: true
    train:
      target: ldm.data.meta.Trainset
      params:
        size: 256
    validation:
      target: ldm.data.meta.Validset
      params:
        size: 256

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 5
        increase_log_steps: false
  trainer:
    benchmark: true
    accumulate_grad_batches: 2
    accelerator: ddp
    gpus: 2,3
